### ISSUE TITLE
ROBLOX does not respond 302 if not logged in

### ISSUE THREAD

**Issue by FroastJ** [Voiliax/RbxPHP#1]
Did some testing and change-rank API won't actually respond 302 (or anything different, for that matter) when you are not logged in.

I think the only way to work this would be to login periodically (every 24-48 hours).

**Comment by Voiliax** [comment]
Based on my testings, they do respond when the cookie is invalid.

**Comment by FroastJ** [comment]
I thought so too, but I ran into some problems yesterday with logging in and from what I can see right now it returns 200 even if you don't have a cookie header.

**Comment by FroastJ** [comment]
I did not find this problem with this specific file but I suspect it may be in it.

**Comment by Voiliax** [comment]
I believe the reason for 302 redirect error is because the cookie I'm inputting is invalid, thus ROBLOX errors and redirects you to their error page. This can also be produced by inputting non-integer groupId, roleSetId, etc.

**Comment by FroastJ** [comment]
![screenshot 2015-04-10 at 11 06 32 pm](https://cloud.githubusercontent.com/assets/8083858/7097491/4b59fa5a-dfd6-11e4-8bbb-4f05e00e7752.png)
This is what I did for testing.

**Comment by Voiliax** [comment]
That website is nice. Anyway I did some testing again and it seems you're right. For now I'll just update ROBLOSECURITY when success is false. I'll try to find a better solution later if possible.
